spring:
  profiles:
    active: dev
  application:
    name: account-service
  datasource:
    url: ${ACCOUNT_DATASOURCE_URL}
    username: ${ACCOUNT_DATASOURCE_USERNAME}
    password: ${ACCOUNT_DATASOURCE_PASSWORD}
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1

omp:
  account-service-endpoint: ${ACCOUNT_SERVICE_ENDPOINT:http://account-service:8082}
