spring:
  datasource:
    url: jdbc:mysql://localhost:3306/omp_test?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: gisnci
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
server:
  port: 8082

omp:
  account-service-endpoint: http://localhost:8082
